### ISSUE TITLE
Errore nel file response.php

### ISSUE THREAD

**Issue by abmcr** [gestpay/php5-gestpay-starter#1]
at the row 17 there is an URL failed

$wsdl = "httpgit s://ecomms2s.sella.it/gestpay/gestpayws/WSCryptDecrypt.asmx?WSDL"; //PRODUCTION

the correct line is

$wsdl = "https://ecomms2s.sella.it/gestpay/gestpayws/WSCryptDecrypt.asmx?WSDL"; //PRODUCTION

**Comment by musikele** [comment]
Thank you for opening the issue, it has been fixed.

**Comment by endelwar** [comment]
also this line has to be fixed https://github.com/gestpay/php5-gestpay-starter/blob/master/index.php#L55

**Comment by musikele** [comment]
What is the problem with this line, @endelwar ? I think the only fix is to change `testecomm.sella.it` with `sandbox.gestpay.net`, but in any case the example should work, too.

**Comment by endelwar** [comment]
That's the error :)
I've received a PR on [pepeverde/GestPayWS](https://github.com/pepeverde/GestPayWS) library: if you make a soap request on testecomm.sella.it with peer_verify_name=true you'll receive an error because peer name doesn't match sandbox.gestpay.net

**Comment by musikele** [comment]
fatto :)
